<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_46FB2BCE11F8FB707430BA4F23</name>
   <tag></tag>
   <elementGuidId>8516125c-9462-42be-b0b8-d6e94c0a85cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ng-include/div[1]/div[3]/ui-view/div/div[2]/div[2]/section/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>terminal-viewport ps-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ps-id</name>
      <type>Main</type>
      <value>91f35cb6-1caa-802c-41af-00d81a3949a9</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>46FB2BCE11F8FB707430BA4F232B85D22467CBBA@/:>_</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ng-include/div[1]/div[3]/ui-view/div/div[2]/div[2]/section/div[1]</value>
   </webElementProperties>
</WebElementEntity>
