<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>4bec60f3-ac68-4e4a-ae29-59d372d12f1c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b-btn b-btn_green js-environment-build ng-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>environmentSimpleViewCtrl.buildCompleted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>environmentSimpleViewCtrl.closePopup()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Close
			</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngdialog1&quot;)/div[@class=&quot;ngdialog-overlay&quot;]/div[@class=&quot;ngdialog-content&quot;]/div[@class=&quot;b-popup b-popup_auto-width&quot;]/form[@class=&quot;ng-valid-maxlength ng-dirty ng-valid-parse ng-valid ng-valid-required ng-submitted&quot;]/div[@class=&quot;b-popup__footer b-popup__footer_undertable&quot;]/button[@class=&quot;b-btn b-btn_green js-environment-build ng-scope&quot;]</value>
   </webElementProperties>
</WebElementEntity>
