<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply</name>
   <tag></tag>
   <elementGuidId>4b8eb23d-ed65-4cdf-a695-b4a1b21c8058</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b-btn b-btn_green ng-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!environmentSimpleViewCtrl.isEditing</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>environmentSimpleViewCtrl.buildEnvironmentByJoint()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Apply
          </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js csstransitions ng-scope&quot;]/body[1]/ng-include[@class=&quot;ng-scope&quot;]/div[@class=&quot;b-content ng-scope&quot;]/div[@class=&quot;b-workspace&quot;]/ui-view[@class=&quot;ng-scope&quot;]/div[@class=&quot;b-workspace__environments ng-scope&quot;]/div[@class=&quot;b-workspace__content b-workspace__content_cloud-env&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;b-cloud ng-scope&quot;]/div[@class=&quot;b-cloud__space&quot;]/div[@class=&quot;b-cloud-space b-cloud-space_border-right&quot;]/div[@class=&quot;b-cloud-space__work&quot;]/div[@class=&quot;b-cloud-create-buttons&quot;]/button[@class=&quot;b-btn b-btn_green ng-scope&quot;]</value>
   </webElementProperties>
</WebElementEntity>
