<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_b-form-input b-form-inpu</name>
   <tag></tag>
   <elementGuidId>a42d76b1-7183-4ea3-ac2f-a97a0370efda</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b-form-input b-form-input_full ng-touched ng-dirty ng-invalid ng-invalid-email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focus-input</name>
      <type>Main</type>
      <value>currentUserCtrl.getRegistrationFormVisibilityStatus()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>currentUserCtrl.hub.login</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your Email address</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hub-button&quot;)/div[@class=&quot;b-hub-status__dropdown ng-scope b-hub-status__dropdown_open&quot;]/div[@class=&quot;ng-scope&quot;]/form[@class=&quot;ng-dirty ng-invalid ng-invalid-email&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;b-form-group g-margin-bottom&quot;]/input[@class=&quot;b-form-input b-form-input_full ng-touched ng-dirty ng-invalid ng-invalid-email&quot;]</value>
   </webElementProperties>
</WebElementEntity>
