<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_login</name>
   <tag></tag>
   <elementGuidId>208136af-249b-49d3-8de1-695248e1d49d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b-form-input b-form-input_full ng-untouched ng-valid ng-dirty ng-valid-parse</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>loginCtrl.name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focus-input</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js csstransitions ng-scope&quot;]/body[@class=&quot;b-body&quot;]/ng-include[@class=&quot;ng-scope&quot;]/ui-view[@class=&quot;ng-scope&quot;]/div[@class=&quot;b-login ng-scope&quot;]/div[@class=&quot;b-login__form b-login__form_center&quot;]/div[@class=&quot;b-workspace b-workspace_login ng-scope&quot;]/div[@class=&quot;b-workspace__content&quot;]/div[@class=&quot;b-form&quot;]/form[@class=&quot;ng-valid ng-valid-pattern ng-dirty ng-valid-parse&quot;]/div[@class=&quot;b-form__wrapper g-margin-bottom-half&quot;]/input[@class=&quot;b-form-input b-form-input_full ng-untouched ng-valid ng-dirty ng-valid-parse&quot;]</value>
   </webElementProperties>
</WebElementEntity>
